// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"w-full border-b shadow\"><nav class=\"flex py-2 px-2 justify-between items-center max-w-6xl mx-auto\" x-data=\"{ showDropdown: false }\"><div class=\"flex items-center space-x-2\"><img src=\"/static/logo.svg\" width=\"48\" height=\"48\" alt=\"Orçamento Auto logo\"><div class=\"font-extrabold hidden md:block md:text-xl uppercase\">Orçamento Auto</div></div><div x-show=\"showDropdown\" x-transition class=\"absolute bg-gray-100 top-[68px] right-2 left-2 border rounded-md\"><ul class=\"flex flex-col text-xl space-y-4 p-3 font-medium\"><li><a href=\"#\" class=\"font-medium hover:text-primary\">Vantagens</a></li><li><a href=\"#\" class=\"font-medium hover:text-primary\">Como funciona</a></li></ul></div><div class=\"flex items-center space-x-3 md:space-x-5\"><button @click=\"showDropdown = !showDropdown\" class=\"block rounded bg-gray-100 p-2.5 text-gray-800 transition hover:text-gray-800/75 md:hidden focus:ring-gray-300 focus:ring-2\"><span class=\"sr-only\">Alternar menu</span> <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button><div class=\"hidden md:block\"><ul class=\"flex space-x-5 font-medium\"><li><a href=\"#\" class=\"font-medium hover:text-primary\">Vantagens</a></li><li><a href=\"#\" class=\"font-medium hover:text-primary\">Como funciona</a></li></ul></div><a href=\"/login\" class=\"btn btn-primary text-white text-base\">Entrar</a></div></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
