// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"flex items-center w-full shadow\"><nav class=\"w-full flex py-2 px-2 justify-between items-center max-w-6xl mx-auto\" x-data=\"{ showDropdown: false }\"><div class=\"flex items-center space-x-2\"><img :src=\"$store.theme.isDark ? &#39;/static/logo-site-dark.svg&#39; : &#39;/static/logo-site.svg&#39;\" width=\"48\" height=\"48\" alt=\"Orçamento Auto logo\"><div class=\"font-extrabold hidden md:block md:text-xl uppercase\">Orçamento Auto</div></div><div x-show=\"showDropdown\" x-transition class=\"absolute bg-base-100 top-[68px] right-2 left-2 border rounded-md\"><ul class=\"flex flex-col text-xl space-y-4 p-3 font-medium\"><li><a href=\"#\">Vantagens</a></li><li><a href=\"#\">Como funciona</a></li><li class=\"self-end\"><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemeToggle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></li></ul></div><div class=\"flex items-center space-x-3 md:space-x-5\"><button @click=\"showDropdown = !showDropdown\" class=\"block rounded p-2.5 transition md:hidden focus:ring-2\"><span class=\"sr-only\">Alternar menu</span> <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button><div class=\"hidden md:block ml-auto\"><ul class=\"flex space-x-5 font-medium text-lg\"><li><a href=\"#\" class=\"hover:text-primary\">Vantagens</a></li><li><a href=\"#\" class=\"hover:text-primary\">Como funciona</a></li></ul></div><a href=\"/entrar\" class=\"btn btn-primary text-base\">Entrar</a><div></div></div></nav><div class=\"mr-10 hidden md:block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemeToggle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
