// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"time"

	"github.com/gmtborges/orcamento-auto/types"
)

func getAutoCategoryNameFromBiddingItems(biddingItems []types.BiddingItemModel) string {
	var autoCategoryDesc string
	if len(biddingItems) < 3 {
		for i, item := range biddingItems {
			if i > 0 {
				autoCategoryDesc += ", "
			}
			autoCategoryDesc += item.AutoCategoryDescription
		}
	} else {
		autoCategoryDesc = fmt.Sprintf("%s, %s, %s ...",
			biddingItems[0].AutoCategoryDescription,
			biddingItems[1].AutoCategoryDescription,
			biddingItems[2].AutoCategoryDescription,
		)
	}
	return autoCategoryDesc
}

func biddingStatus(status types.BiddingStatus) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch status {
		case types.BiddingStatusAwaitingOffer:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td class=\"font-bold text-info\">Aguardando proposta</td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case types.BiddingStatusPending:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td class=\"font-bold text-warning\">Pendente</td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case types.BiddingStatusFinished:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td class=\"font-bold text-success\">Finalizado</td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case types.BiddingStatusCanceled:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<td class=\"font-bold text-error\">Cancelado</td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

func formatRelativeTime(t time.Time) string {
	now := time.Now()
	diff := now.Sub(t)
	if diff.Seconds() < 60 {
		return fmt.Sprintf("agora a pouco")
	}
	if diff.Minutes() < 60 {
		if int(diff.Minutes()) == 1 {
			return fmt.Sprintf("1 minuto atrás")
		}
		return fmt.Sprintf("%d minutos atrás", int(diff.Minutes()))
	}
	if diff.Hours() < 24 {
		if int(diff.Hours()) == 1 {
			return fmt.Sprintf("1 hora atrás")
		}
		return fmt.Sprintf("%d horas atrás", int(diff.Hours()))
	}
	if diff.Hours() < 48 {
		return fmt.Sprintf("ontem")
	}
	if diff.Hours() < 168 {
		if int(diff.Hours()/24) == 1 {
			return fmt.Sprintf("1 dia atrás")
		}
		return fmt.Sprintf("%d dias atrás", int(diff.Hours()/24))
	}
	if diff.Hours() < 720 {
		if int(diff.Hours()/168) == 1 {
			return fmt.Sprintf("1 semana atrás")
		}
		return fmt.Sprintf("%d semanas atrás", int(diff.Hours()/168))
	}
	if diff.Hours() < 8760 {
		if int(diff.Hours()/720) == 1 {
			return fmt.Sprintf("1 mês atrás")
		}
		return fmt.Sprintf("%d meses atrás", int(diff.Hours()/720))
	}
	return t.Format("02/01/2006")
}

func OfferList(vm types.OfferIndexViewModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"bidding-table\" class=\"flex flex-col w-full overflow-x-auto md:overflow-hidden\"><div class=\"min-w-[1200px] w-full\">Carro agrupado com items do orçamento e propostas de cada item</div><div class=\"flex justify-end items-center gap-4\"><p class=\"mt-2\">Total: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", vm.Count))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/offer/partials/offer_list.templ`, Line: 88, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><div class=\"join mt-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := 1; i <= vm.TotalPages; i++ {
			var templ_7745c5c3_Var4 = []any{"join-item", "btn", templ.KV("btn-active", vm.CurrentPage == i)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/offer/partials/offer_list.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-get=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(string(templ.URL(fmt.Sprintf("/propostas?p=%d", i))))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/offer/partials/offer_list.templ`, Line: 93, Col: 67}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-target=\"#bidding-table\" hx-swap=\"innerHTML\" hx-push-url=\"true\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", i))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/offer/partials/offer_list.templ`, Line: 98, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
