-- +goose Up
-- +goose StatementBegin
CREATE TABLE empresas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(255) NOT NULL,
  tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('ORG', 'AUTO')),
  estado VARCHAR(100) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  endereco VARCHAR(255),
  numero_telefone VARCHAR(25),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  empresa_id BIGINT,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE
);

CREATE TABLE funcoes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO
  funcoes (nome)
VALUES
  ('ADMIN'),
  ('VISUALIZAR'),
  ('EDITAR');

CREATE TABLE usuarios_funcoes (
  funcao_id BIGINT REFERENCES funcoes (id),
  usuario_id BIGINT REFERENCES usuarios (id),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (funcao_id, usuario_id)
);

CREATE TABLE auto_categorias (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(100) NOT NULL,
  tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('PRODUTO', 'SERVICO'))
);

CREATE TABLE empresas_auto_categorias (
  auto_categoria_id BIGINT REFERENCES auto_categorias (id),
  empresa_id BIGINT REFERENCES empresas (id),
  PRIMARY KEY (auto_categoria_id, empresa_id)
);

CREATE TABLE orcamentos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT,
  usuario_id BIGINT NOT NULL,
  associado_nome VARCHAR(255) NOT NULL,
  veiculo_marca VARCHAR(255) NOT NULL,
  veiculo_nome VARCHAR(255) NOT NULL,
  veiculo_ano INT NOT NULL,
  veiculo_cor VARCHAR(50) NOT NULL,
  observacao TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'AGUARDANDO_PROPOSTA' CHECK (
    status IN (
      'AGUARDANDO_PROPOSTA',
      'PENDENTE',
      'CANCELADO',
      'FINALIZADO'
    )
  ),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE orcamento_itens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  orcamento_id BIGINT NOT NULL,
  observacao TEXT,
  auto_categoria_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ABERTO' CHECK (
    status IN (
      'ABERTO',
      'PROPOSTA_RECEBIDA',
      'PROPOSTA_ACEITA',
      'CANCELADO'
    )
  ),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orcamento_id) REFERENCES orcamentos (id) ON DELETE CASCADE,
  FOREIGN KEY (auto_categoria_id) REFERENCES auto_categorias (id) ON DELETE NO ACTION
);

CREATE TABLE auto_propostas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT NOT NULL,
  orcamento_item_id BIGINT NOT NULL,
  preco NUMERIC(10, 2),
  aceita BOOLEAN NOT NULL DEFAULT FALSE,
  detalhes TEXT,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE,
  FOREIGN KEY (orcamento_item_id) REFERENCES orcamento_itens (id) ON DELETE CASCADE
);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE auto_propostas;

DROP TABLE orcamento_itens;

DROP TABLE orcamentos;

DROP TABLE usuarios_funcoes;

DROP TABLE funcoes;

DROP TABLE usuarios;

DROP TABLE empresas_auto_categorias;

DROP TABLE empresas;

DROP TABLE auto_categorias;

-- +goose StatementEnd
