-- +goose Up
-- +goose StatementBegin
CREATE TABLE companies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL CHECK (type IN ('ORG', 'AUTO')),
  state VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  cellphone VARCHAR(25),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  company_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
);

CREATE TABLE roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO
  roles (name)
VALUES
  ('ADMIN'),
  ('VIEW'),
  ('EDIT');

CREATE TABLE users_roles (
  role_id BIGINT REFERENCES roles (id),
  user_id BIGINT REFERENCES users (id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (role_id, user_id)
);

CREATE TABLE auto_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  description VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL CHECK (type IN ('PRODUCT', 'SERVICE'))
);

CREATE TABLE companies_auto_categories (
  auto_category_id BIGINT REFERENCES auto_categories (id),
  company_id BIGINT REFERENCES companies (id),
  PRIMARY KEY (auto_category_id, company_id)
);

CREATE TABLE biddings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT,
  user_id BIGINT NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  vehicle_brand VARCHAR(255) NOT NULL,
  vehicle_name VARCHAR(255) NOT NULL,
  vehicle_year INT NOT NULL,
  vehicle_color VARCHAR(50) NOT NULL,
  notes TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'AWAITING_OFFER' CHECK (
    status IN (
      'AWAITING_OFFER',
      'PENDING',
      'CANCELED',
      'FINISHED'
    )
  ),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE bidding_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bidding_id BIGINT NOT NULL,
  notes TEXT,
  auto_category_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'OPEN' CHECK (
    status IN (
      'OPEN',
      'OFFER_RECEIVED',
      'OFFER_ACCEPTED',
      'CANCELED'
    )
  ),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bidding_id) REFERENCES biddings (id) ON DELETE CASCADE,
  FOREIGN KEY (auto_category_id) REFERENCES auto_categories (id) ON DELETE NO ACTION
);

CREATE TABLE auto_offers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL,
  bidding_item_id BIGINT NOT NULL,
  price NUMERIC(10, 2),
  accepted BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  FOREIGN KEY (bidding_item_id) REFERENCES bidding_items (id) ON DELETE CASCADE
);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE auto_offers;

DROP TABLE bidding_items;

DROP TABLE biddings;

DROP TABLE users_roles;

DROP TABLE roles;

DROP TABLE users;

DROP TABLE companies_auto_categories;

DROP TABLE companies;

DROP TABLE auto_categories;

-- +goose StatementEnd
