// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AutoCategories       string
	AutoOffers           string
	AutoStores           string
	AutoStoresCategories string
	Biddings             string
	Companies            string
	Employers            string
	Users                string
}{
	AutoCategories:       "auto_categories",
	AutoOffers:           "auto_offers",
	AutoStores:           "auto_stores",
	AutoStoresCategories: "auto_stores_categories",
	Biddings:             "biddings",
	Companies:            "companies",
	Employers:            "employers",
	Users:                "users",
}
