// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AutoOffers", testAutoOffersUpsert)

	t.Run("AutoPartsCategories", testAutoPartsCategoriesUpsert)

	t.Run("AutoStores", testAutoStoresUpsert)

	t.Run("Biddings", testBiddingsUpsert)

	t.Run("Companies", testCompaniesUpsert)

	t.Run("Users", testUsersUpsert)
}
